CREATE TABLE `phone_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `model` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `color` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `capacity` int(11) NOT NULL,
  `remarks` text COLLATE utf8_unicode_ci,
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `state` int(11) NOT NULL DEFAULT '1',
  `ip` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `agent` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `send` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '发货时间',
  `sign` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '签收时间',
  `reply` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '回件日期',
  `text` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '跟单说明',
  `user_id` int(11) DEFAULT NULL COMMENT '锁定工号',
  `express_number` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '快递单号',
  `ad_id` int(11) DEFAULT NULL COMMENT '广告ID',
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
